/**
 * Form 表單的動作。
 */
export enum DataType {
  TRAIN_KIND = 'TRAIN_KIND',
  STOP_KIND = 'STOP_KIND',
  TEMPLATE = 'TEMPLATE',
  YES_NO = 'YES_NO',
  LANGUAGE = 'LANGUAGE',
  PAY_METHOD = 'PAY_METHOD',
  SEAT_NO_LIST = 'SEAT_NO_LIST',
  CAR_NO_LIST = 'CAR_NO_LIST',
  SHEET_NAME = 'SHEET_NAME',
  DATA_MAPPING = 'DATA_MAPPING',
  CUSTOMISATION = 'CUSTOMISATION',
}
