/**
 * 維護權限。
 */
export enum MaintainPermission {
  USER_MAINTAIN = 'USER_MAINTAIN',
  ROLE_MAINTAIN = 'ROLE_MAINTAIN',
  FUNCTION_MAIMTAIN = 'FUNCTION_MAINTAIN',
  GROUP_MAINTAIN = 'GROUP_MAINTAIN',
  ROLE_FUNCTION_MAINTAIN = 'ROLE_FUNCTION_MAINTAIN',
  GROUP_ROLE_MAINTAIN = 'GROUP_ROLE_MAINTAIN',
  SETTING_MAINTAIN = 'SETTING_MAINTAIN',
  USER_ROLE_MAINTAIN = 'USER_ROLE_MAINTAIN',
  USER_GROUP_MAINTAIN = 'USER_GROUP_MAINTAIN',
}
